#!/usr/bin/with-contenv bash
. /opt/scripts/install.rc;
__check_status;

echo "================================================================================"
echo "Installing YYDecode."
echo "================================================================================"
echo "=== Downloading ..."
curl -s -L -o /tmp/yydecode.deb 'https://other.mvia.ca/yydecode_0.2.10-4_amd64.deb' 2>&1 > /dev/null || __exit 14;
echo "--- Done."
echo ""
echo "=== Installing ..."
dpkg --install /tmp/yydecode.deb || __exit 15;
rm /tmp/yydecode.deb
echo "--- Done."
hash -r;
echo ""
__exit 0;

